Repository OCA/rest-framework, pull requests merged in 2020-08, with the labels that each got.

#74 Use the latest pylint-odoo
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#72 [12.0][FIX][base_rest] issue when _description is None
  base_rest/components/service.py
Labels: approved, bot is merging ⏳

#75 [13.0][PORT] 74 from 12.0
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  setup/graphql_base/setup.py
Labels: bot is merging ⏳

#65 base_rest: call openapi methods only once
  base_rest/components/service.py
Labels: bot is merging ⏳

#77 [13.0] [FIX] base_rest Fix issue when description is False
  base_rest/components/service.py
Labels: approved, base_rest, bot is merging ⏳, needs review

#76 base_rest: improve exception wrapped info
  base_rest/http.py
Labels: approved, bot is merging ⏳, needs review

#79 [12.0]base_rest: improve exception wrapped info
  base_rest/http.py
Labels: bot is merging ⏳

#80 base_rest: pick exception info from all exc types
  base_rest/http.py
Labels: bot is merging ⏳, needs review
