Repository OCA/rest-framework, pull requests merged in 2021-01, with the labels that each got.

#99 [13.0] Add handlers to delegate validators
  base_rest/components/__init__.py
  base_rest/components/cerberus_validator.py
  base_rest/models/rest_service_registration.py
  base_rest/restapi.py
  base_rest/tests/common.py
  base_rest/tests/test_cerberus_validator.py
  base_rest_datamodel/restapi.py
Labels: approved, bot is merging ⏳

#97 [14.0][FIX] base_rest: Allows to scroll in case of overflow into the swagge…
  base_rest/views/openapi_template.xml
Labels: bot is merging ⏳

#101 [12.0] Add handlers to delegate validators
  base_rest/components/__init__.py
  base_rest/components/cerberus_validator.py
  base_rest/models/rest_service_registration.py
  base_rest/restapi.py
  base_rest/tests/common.py
  base_rest/tests/test_cerberus_validator.py
  base_rest_datamodel/restapi.py
Labels: 12.0, bot is merging ⏳

#102 [14.0] Add handlers to delegate validators
  base_rest/components/__init__.py
  base_rest/components/cerberus_validator.py
  base_rest/models/rest_service_registration.py
  base_rest/restapi.py
  base_rest/tests/common.py
  base_rest/tests/test_cerberus_validator.py
  base_rest_datamodel/restapi.py
Labels: 14.0, bot is merging ⏳
