Repository OCA/rest-framework, pull requests merged in 2021-11, with the labels that each got.

#214 base_rest: decouple rest route registration
  base_rest/core.py
  base_rest/http.py
  base_rest/models/rest_service_registration.py
Labels: needs review, bot is merging ⏳

#177 [13.0][ADD] model_serializer: module to facilitate the (de)serialization of Odoo Models into DataModels
  __init__.py
  model_serializer/README.rst
  model_serializer/__init__.py
  model_serializer/__manifest__.py
  model_serializer/builder.py
  model_serializer/core.py
  model_serializer/field_converter.py
  model_serializer/readme/CONTRIBUTORS.rst
  model_serializer/readme/DESCRIPTION.rst
  model_serializer/readme/HISTORY.rst
  model_serializer/readme/USAGE.rst
  model_serializer/serializers.py
  model_serializer/static/description/index.html
  model_serializer/tests/__init__.py
  model_serializer/tests/test_model_serializer.py
Labels: bot is merging ⏳

#193 [14.0][ADD] model_serializer: module to facilitate the (de)serialization of Odoo Models into DataModels
  model_serializer/README.rst
  model_serializer/__init__.py
  model_serializer/__manifest__.py
  model_serializer/builder.py
  model_serializer/core.py
  model_serializer/field_converter.py
  model_serializer/readme/CONTRIBUTORS.rst
  model_serializer/readme/DESCRIPTION.rst
  model_serializer/readme/HISTORY.rst
  model_serializer/readme/USAGE.rst
  model_serializer/serializers.py
  model_serializer/static/description/index.html
  model_serializer/tests/__init__.py
  model_serializer/tests/test_model_serializer.py
Labels: needs review, bot is merging ⏳, 14.0

#219 [14.0] base_rest: api docs improvements
  base_rest/apispec/base_rest_service_apispec.py
  base_rest/apispec/rest_method_security_plugin.py
  base_rest/controllers/api_docs.py
  base_rest/static/src/js/swagger_ui.js
  base_rest/views/openapi_template.xml
Labels: approved, bot is merging ⏳
