Repository OCA/rest-framework, pull requests merged in 2021-07, with the labels that each got.

#176 [13.0][FIX] fix unit test w/ odoo test suite
  base_rest/tests/common.py
  base_rest/tests/test_cerberus_validator.py
  datamodel/tests/common.py
Labels: approved, bot is merging ⏳

#168 [13.0][CHG] datamodel: Use more permissive licence: AGPL-> LGPL
  base_rest_datamodel/__manifest__.py
  datamodel/__manifest__.py
  datamodel/builder.py
  datamodel/core.py
  datamodel/datamodels/base.py
  datamodel/fields.py
  datamodel/tests/common.py
  datamodel/tests/test_build_datamodel.py
Labels: approved, bot is merging ⏳, ready to merge

#174 [14.0] base_rest multiple http methods and cors OPTIONS
  base_rest/restapi.py
Labels: approved, bot is merging ⏳

#122 [14.0] Fix issue with datamodel, recursion limit
  datamodel/README.rst
  datamodel/core.py
  datamodel/readme/CONTRIBUTORS.rst
  datamodel/readme/DESCRIPTION.rst
  datamodel/readme/ROADMAP.rst
  datamodel/readme/USAGE.rst
  datamodel/static/description/index.html
  datamodel/tests/test_build_datamodel.py
Labels: bot is merging ⏳

#120 [12.0] Fix issue with datamodel, recursion limit
  base_rest/tests/common.py
  base_rest/tests/test_cerberus_validator.py
  datamodel/README.rst
  datamodel/core.py
  datamodel/readme/CONTRIBUTORS.rst
  datamodel/readme/DESCRIPTION.rst
  datamodel/readme/ROADMAP.rst
  datamodel/readme/USAGE.rst
  datamodel/static/description/index.html
  datamodel/tests/common.py
  datamodel/tests/test_build_datamodel.py
Labels: bot is merging ⏳

#121 [13.0] Fix issue with datamodel, recursion limit
  datamodel/README.rst
  datamodel/core.py
  datamodel/readme/CONTRIBUTORS.rst
  datamodel/readme/DESCRIPTION.rst
  datamodel/readme/ROADMAP.rst
  datamodel/readme/USAGE.rst
  datamodel/static/description/index.html
  datamodel/tests/test_build_datamodel.py
Labels: bot is merging ⏳

#180 [14.0] base_rest: improve service context and security
  base_rest/apispec/base_rest_service_apispec.py
  base_rest/apispec/rest_method_param_plugin.py
  base_rest/apispec/rest_method_security_plugin.py
  base_rest/components/__init__.py
  base_rest/components/service.py
  base_rest/components/service_context_provider.py
  base_rest/controllers/api_docs.py
  base_rest/controllers/main.py
  base_rest/models/rest_service_registration.py
  base_rest/restapi.py
  base_rest/tests/common.py
  base_rest/tests/test_controller_builder.py
  base_rest_datamodel/__manifest__.py
  base_rest_demo/tests/data/partner_api.json
  base_rest_demo/tests/data/partner_image_api.json
  base_rest_demo/tests/data/ping_api.json
  base_rest_demo/tests/test_openapi.py
Labels: approved, bot is merging ⏳

#181 [14.0] base_rest_auth_api_key: Add support for the auth_api_key security policy into the openapi documentation
  base_rest_auth_api_key/README.rst
  base_rest_auth_api_key/__init__.py
  base_rest_auth_api_key/__manifest__.py
  base_rest_auth_api_key/apispec/__init__.py
  base_rest_auth_api_key/apispec/rest_method_security_plugin.py
  base_rest_auth_api_key/components/__init__.py
  base_rest_auth_api_key/components/service.py
  base_rest_auth_api_key/readme/CONTRIBUTORS.rst
  base_rest_auth_api_key/readme/DESCRIPTION.rst
  base_rest_auth_api_key/static/description/icon.png
  base_rest_auth_api_key/static/description/index.html
  setup/base_rest_auth_api_key/odoo/addons/base_rest_auth_api_key
  setup/base_rest_auth_api_key/setup.py
Labels: bot is merging ⏳
