Repository OCA/rest-framework, pull requests merged in 2021-04, with the labels that each got.

#149 [10.0]Allow disabling a service when _is_rest_service_component is False
  base_rest/controllers/api_docs.py
Labels: bot is merging ⏳

#150 [13.0][FIX] base_rest: do not crash on missing description
  base_rest/apispec/base_rest_service_apispec.py
Labels: 13.0, bot is merging ⏳

#151 [14.0][FIX] base_rest: do not crash on missing description
  base_rest/apispec/base_rest_service_apispec.py
Labels: 14.0, bot is merging ⏳

#147 [13.0] rest_log misc improvements
  base_rest/http.py
  rest_log/components/service.py
  rest_log/models/rest_log.py
  rest_log/readme/CONFIGURE.rst
  rest_log/tests/test_db_logging.py
  rest_log/views/rest_log_views.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge
