Repository OCA/rest-framework, pull requests merged in 2021-02, with the labels that each got.

#106 [13.0] Add rest_log
  base_rest/tests/common.py
  base_rest/tests/test_controller_builder.py
  base_rest/tests/test_openapi_generator.py
  base_rest/views/base_rest_view.xml
  rest_log/README.rst
  rest_log/__init__.py
  rest_log/__manifest__.py
  rest_log/components/__init__.py
  rest_log/components/service.py
  rest_log/data/ir_config_parameter_data.xml
  rest_log/data/ir_cron_data.xml
  rest_log/exceptions.py
  rest_log/hooks.py
  rest_log/models/__init__.py
  rest_log/models/rest_log.py
  rest_log/readme/CONFIGURE.rst
  rest_log/readme/CONTRIBUTORS.rst
  rest_log/readme/CREDITS.rst
  rest_log/readme/DESCRIPTION.rst
  rest_log/readme/HISTORY.rst
  rest_log/security/groups.xml
  rest_log/security/ir.model.access.csv
  rest_log/static/description/index.html
  rest_log/tests/__init__.py
  rest_log/tests/common.py
  rest_log/tests/test_db_logging.py
  rest_log/views/menu.xml
  rest_log/views/rest_log_views.xml
  setup/rest_log/odoo/addons/rest_log
  setup/rest_log/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#115 rest_log: fix init hook
  rest_log/__init__.py
  rest_log/__manifest__.py
  rest_log/hooks.py
Labels: bot is merging ⏳

#114 rest_log: re-license to LGPL
  rest_log/__manifest__.py
  rest_log/components/service.py
  rest_log/hooks.py
  rest_log/models/rest_log.py
  rest_log/security/groups.xml
  rest_log/tests/common.py
  rest_log/tests/test_db_logging.py
Labels: approved, bot is merging ⏳

#110 [12.0][FIX] Check database existence before initializing it
  base_rest/http.py
Labels: approved, bot is merging ⏳, ready to merge

#112 [14.0][FIX] Check database existence before initializing it
  base_rest/http.py
Labels: bot is merging ⏳
