Repository OCA/rest-framework, pull requests merged in 2022-12, with the labels that each got.

#319 [14.0] [IMP] base_rest: Add authenticated partner and env property on base.r…
  base_rest/components/service.py
Labels: approved, bot is merging ⏳

#320 [14.0][IMP] base_rest: if method call result is already an werkzeug.Respons…
  base_rest/components/service.py
Labels: bot is merging ⏳

#277 [FIX] 14.0 pydantic: generate schema using field name
  base_rest_demo/tests/data/partner_pydantic_api.json
  base_rest_pydantic/restapi.py
Labels: approved, ready to merge, bot is merging ⏳
