Repository OCA/rest-framework, pull requests merged in 2022-09, with the labels that each got.

#285 [15.0] [IMP] `base_rest`: bump icon style
  base_rest/static/description/icon.png
  base_rest/static/description/icon.svg
Labels: approved, bot is merging ⏳

#279 [FIX] base_rest_pydantic: forword service to PydanticModel.from_params
  base_rest_pydantic/restapi.py
  base_rest_pydantic/tests/test_from_params.py
Labels: approved, ready to merge, bot is merging ⏳

#292 [15.0][FIX] base_rest_pydantic: forword service to PydanticModel.from_params
  base_rest_pydantic/restapi.py
  base_rest_pydantic/tests/test_from_params.py
Labels: bot is merging ⏳

#293 [16.0][FIX] base_rest_pydantic: forword service to PydanticModel.from_params
  base_rest_pydantic/restapi.py
  base_rest_pydantic/tests/test_from_params.py
Labels: bot is merging ⏳
