Repository OCA/rest-framework, pull requests merged in 2022-10, with the labels that each got.

#297 [14.0] base_rest: do not leak passwords in exception msg
  base_rest/http.py
Labels: approved, bot is merging ⏳

#298 [14.0] rest_log: add sanitize params hook
  rest_log/components/service.py
Labels: approved, bot is merging ⏳

#272 [15.0][FIX] base_rest: `swagger_ui.js` is (sometimes) loaded first, causing crashes
  base_rest/__manifest__.py
Labels: approved, ready to merge, bot is merging ⏳

#302 [16][FIX] base_rest: add explicit dependency to `web`, otherwise `swagger…
  base_rest/__manifest__.py
Labels: bot is merging ⏳

#296 [IMP] rest_log: handle odoo.http.Response objects in logs
  rest_log/components/service.py
  rest_log/tests/test_db_logging.py
Labels: approved, ready to merge, bot is merging ⏳

#303 [14.0][FWD] rest_log imp/fix
  rest_log/components/service.py
  rest_log/tests/test_db_logging.py
Labels: bot is merging ⏳

#305 [14.0] rest_log: add more hooks
  rest_log/components/service.py
Labels: approved, bot is merging ⏳
