Repository OCA/rest-framework, pull requests merged in 2022-02, with the labels that each got.

#246 [14.0][ADD] extendable: New addon to alllow usage of the Extendable python …
  extendable/README.rst
  extendable/__init__.py
  extendable/__manifest__.py
  extendable/models/__init__.py
  extendable/models/extendable_registry_loader.py
  extendable/models/ir_http.py
  extendable/readme/CONTRIBUTORS.rst
  extendable/readme/DESCRIPTION.rst
  extendable/readme/ROADMAP.rst
  extendable/readme/USAGE.rst
  extendable/registry.py
  extendable/static/description/index.html
  extendable/tests/__init__.py
  extendable/tests/common.py
  requirements.txt
  setup/extendable/odoo/addons/extendable
  setup/extendable/setup.py
Labels: approved, bot is merging ⏳

#245 [IMP] graphql_base: add hook for context
  graphql_base/controllers/main.py
Labels: approved, ready to merge, bot is merging ⏳

#252 [14.0] rest_log: store collection ID when available
  base_rest/controllers/main.py
  rest_log/components/service.py
  rest_log/models/rest_log.py
  rest_log/views/rest_log_views.xml
Labels: enhancement, needs review, approved, bot is merging ⏳
