Repository OCA/rest-framework, pull requests merged in 2022-11, with the labels that each got.

#309 [14.0] [IMP] base_rest: Swagger ui harmonization with odoo ui
  base_rest/static/src/js/swagger_ui.js
  base_rest/static/src/scss/base_rest.scss
Labels: approved, bot is merging ⏳

#310 [15.0][FIX] Update pre-commit rules
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  README.md
Labels: bot is merging ⏳

#311 [16.0][FIX] Update pre-commit rules
  .copier-answers.yml
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  README.md
Labels: bot is merging ⏳

#270 [IMP] Deprecate old API
  base_rest/models/rest_service_registration.py
Labels: bot is merging ⏳, no stale

#301 [15.0][FWD] rest_log: add sanitize params hook
  rest_log/components/service.py
Labels: bot is merging ⏳
