Repository OCA/rest-framework, pull requests merged in 2022-08, with the labels that each got.

#274 Run copier
  .copier-answers.yml
  .editorconfig
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  base_rest_datamodel/__manifest__.py
  base_rest_demo/__manifest__.py
  requirements.txt
Labels: bot is merging ⏳

#271 [MIG] model_serializer: Migration to 15.0
  .pre-commit-config.yaml
  model_serializer/__manifest__.py
  model_serializer/builder.py
  model_serializer/core.py
  model_serializer/readme/HISTORY.rst
  model_serializer/serializers.py
  model_serializer/tests/test_model_serializer.py
  setup/model_serializer/odoo/addons/model_serializer
  setup/model_serializer/setup.py
Labels: bot is merging ⏳

#276 [FIX] base_rest: Patch from the first request
  base_rest/controllers/main.py
  base_rest/readme/CONFIGURE.rst
Labels: approved, ready to merge, bot is merging ⏳

#280 [FIX] base_rest: Patch from the first request
  base_rest/controllers/main.py
  base_rest/readme/CONFIGURE.rst
Labels: bot is merging ⏳

#281 [FIX] model-serializer: `load_only` fields are ignored during loading
  model_serializer/core.py
Labels: bot is merging ⏳

#282 [14.0] model_serializer: add myself as maintainer
  model_serializer/__manifest__.py
Labels: approved, bot is merging ⏳

#253 [13.0][MIG] base_rest_pydantic: backport
  .isort.cfg
  base_rest/apispec/rest_method_param_plugin.py
  base_rest/restapi.py
  base_rest/tests/test_cerberus_list_validator.py
  base_rest/tests/test_cerberus_validator.py
  base_rest_datamodel/restapi.py
  base_rest_datamodel/tests/test_response.py
  base_rest_demo/__init__.py
  base_rest_demo/__manifest__.py
  base_rest_demo/partner.json
  base_rest_demo/partner_image_api.json
  base_rest_demo/ping_api.json
  base_rest_demo/pydantic_models/__init__.py
  base_rest_demo/pydantic_models/country_info.py
  base_rest_demo/pydantic_models/naive_orm_model.py
  base_rest_demo/pydantic_models/partner_info.py
  base_rest_demo/pydantic_models/partner_search_param.py
  base_rest_demo/pydantic_models/partner_short_info.py
  base_rest_demo/pydantic_models/state_info.py
  base_rest_demo/services/__init__.py
  base_rest_demo/services/partner_pydantic_services.py
  base_rest_demo/tests/common.py
  base_rest_demo/tests/data/partner_pydantic_api.json
  base_rest_demo/tests/test_openapi.py
  base_rest_pydantic/README.rst
  base_rest_pydantic/__init__.py
  base_rest_pydantic/__manifest__.py
  base_rest_pydantic/i18n/base_rest_datamodel.pot
  base_rest_pydantic/readme/CONTRIBUTORS.rst
  base_rest_pydantic/readme/DESCRIPTION.rst
  base_rest_pydantic/readme/USAGE.rst
  base_rest_pydantic/restapi.py
  base_rest_pydantic/static/description/icon.png
  base_rest_pydantic/static/description/index.html
  base_rest_pydantic/tests/__init__.py
  base_rest_pydantic/tests/test_from_params.py
  base_rest_pydantic/tests/test_response.py
  datamodel/tests/test_build_datamodel.py
  pydantic/README.rst
  pydantic/__init__.py
  pydantic/__manifest__.py
  pydantic/readme/CONTRIBUTORS.rst
  pydantic/readme/DESCRIPTION.rst
  pydantic/readme/ROADMAP.rst
  pydantic/readme/USAGE.rst
  pydantic/static/description/icon.png
  pydantic/static/description/index.html
  pydantic/utils.py
  requirements.txt
  setup/base_rest_pydantic/odoo/addons/base_rest_pydantic
  setup/base_rest_pydantic/setup.py
  setup/pydantic/odoo/addons/pydantic
  setup/pydantic/setup.py
Labels: bot is merging ⏳
