Repository OCA/rest-framework, pull requests merged in 2023-10, with the labels that each got.

#379 [16.0] base_rest: Define the oauth2 redirect url into swagger ui
  base_rest/readme/newsfragments/.gitignore
  base_rest/readme/newsfragments/379.feature
  base_rest/static/src/js/swagger_ui.js
Labels: bot is merging ⏳

#380 [16.0][IMP] extendable_fastapi: Add generics schemas
  extendable_fastapi/__manifest__.py
  extendable_fastapi/readme/newsfragments/.gitignore
  extendable_fastapi/readme/newsfragments/380.feature
  extendable_fastapi/schemas.py
  fastapi/readme/USAGE.rst
  fastapi/readme/newsfragments/.gitignore
  fastapi/readme/newsfragments/380.feature
  fastapi/schemas.py
  requirements.txt
Labels: approved, bot is merging ⏳

#386 [16.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  datamodel/tests/test_build_datamodel.py
Labels: help wanted, needs review, bot is merging ⏳
