Repository OCA/rest-framework, pull requests merged in 2023-06, with the labels that each got.

#291 [16.0] FastAPI Integration
  extendable_fastapi/README.rst
  extendable_fastapi/__init__.py
  extendable_fastapi/__manifest__.py
  extendable_fastapi/models/__init__.py
  extendable_fastapi/models/fastapi_endpoint.py
  extendable_fastapi/readme/CONTRIBUTORS.rst
  extendable_fastapi/readme/DESCRIPTION.rst
  extendable_fastapi/static/description/icon.png
  extendable_fastapi/static/description/index.html
  fastapi/README.rst
  fastapi/__init__.py
  fastapi/__manifest__.py
  fastapi/context.py
  fastapi/demo/fastapi_endpoint_demo.xml
  fastapi/depends.py
  fastapi/error_handlers.py
  fastapi/fastapi_dispatcher.py
  fastapi/models/__init__.py
  fastapi/models/fastapi_endpoint.py
  fastapi/models/fastapi_endpoint_demo.py
  fastapi/models/ir_rule.py
  fastapi/models/res_lang.py
  fastapi/readme/CONTRIBUTORS.rst
  fastapi/readme/DESCRIPTION.rst
  fastapi/readme/ROADMAP.rst
  fastapi/readme/USAGE.rst
  fastapi/schemas.py
  fastapi/security/fastapi_endpoint.xml
  fastapi/security/ir_rule+acl.xml
  fastapi/security/res_groups.xml
  fastapi/static/description/endpoint_create.png
  fastapi/static/description/icon.png
  fastapi/static/description/index.html
  fastapi/tests/__init__.py
  fastapi/tests/test_fastapi.py
  fastapi/tests/test_fastapi_demo.py
  fastapi/views/fastapi_endpoint.xml
  fastapi/views/fastapi_endpoint_demo.xml
  fastapi/views/fastapi_menu.xml
  requirements.txt
  setup/extendable_fastapi/odoo/addons/extendable_fastapi
  setup/extendable_fastapi/setup.py
  setup/fastapi/odoo/addons/fastapi
  setup/fastapi/setup.py
  test-requirements.txt
Labels: bot is merging ⏳

#341 [DOC] fastapi: documentation fixes
  fastapi/readme/USAGE.rst
Labels: needs review, bot is merging ⏳

#343 [IMP] small changes in fastapi readme
  fastapi/README.rst
  fastapi/readme/USAGE.rst
Labels: approved, bot is merging ⏳

#345 [IMP] fastapi: Add fastapi addons directory structure into documentation
  fastapi/README.rst
  fastapi/dependencies.py
  fastapi/depends.py
  fastapi/models/fastapi_endpoint.py
  fastapi/models/fastapi_endpoint_demo.py
  fastapi/readme/USAGE.rst
  fastapi/static/description/index.html
  fastapi/tests/test_fastapi_demo.py
Labels: bot is merging ⏳

#350 [UPD] rest-framework : fix small typo in doc
  fastapi/readme/USAGE.rst
Labels: bot is merging ⏳

#353 [WIP] fastapi: mount app at root_path instead of prefixing routes and docs URLs
  fastapi/models/fastapi_endpoint.py
  fastapi/tests/test_fastapi_demo.py
Labels: approved, bot is merging ⏳

#347 [16.0][ADD] fastapi_auth_jwt, fastapi_auth_jwt_demo
  fastapi_auth_jwt/README.rst
  fastapi_auth_jwt/__init__.py
  fastapi_auth_jwt/__manifest__.py
  fastapi_auth_jwt/dependencies.py
  fastapi_auth_jwt/readme/DESCRIPTION.rst
  fastapi_auth_jwt/readme/USAGE.rst
  fastapi_auth_jwt_demo/README.rst
  fastapi_auth_jwt_demo/__init__.py
  fastapi_auth_jwt_demo/__manifest__.py
  fastapi_auth_jwt_demo/demo/fastapi_endpoint.xml
  fastapi_auth_jwt_demo/models/__init__.py
  fastapi_auth_jwt_demo/models/fastapi_endpoint.py
  fastapi_auth_jwt_demo/readme/DESCRIPTION.rst
  fastapi_auth_jwt_demo/routers/__init__.py
  fastapi_auth_jwt_demo/routers/auth_jwt_demo_api.py
  fastapi_auth_jwt_demo/tests/__init__.py
  fastapi_auth_jwt_demo/tests/test_fastapi_auth_jwt_demo.py
  setup/fastapi_auth_jwt/odoo/addons/fastapi_auth_jwt
  setup/fastapi_auth_jwt/setup.py
  setup/fastapi_auth_jwt_demo/odoo/addons/fastapi_auth_jwt_demo
  setup/fastapi_auth_jwt_demo/setup.py
Labels: bot is merging ⏳

#339 [13.0] [REF] base_rest: werkzeug 2 compatibility
  base_rest/http.py
Labels: bot is merging ⏳

#348 [16.0] fastapi: eases tests development
  base_rest_demo/tests/common.py
  extendable/__manifest__.py
  extendable/tests/common.py
  extendable_fastapi/tests/__init__.py
  extendable_fastapi/tests/common.py
  fastapi/README.rst
  fastapi/dependencies.py
  fastapi/models/__init__.py
  fastapi/models/fastapi_endpoint_demo.py
  fastapi/readme/USAGE.rst
  fastapi/routers/__init__.py
  fastapi/routers/demo_router.py
  fastapi/schemas.py
  fastapi/static/description/index.html
  fastapi/tests/common.py
  fastapi/tests/test_fastapi.py
  fastapi/tests/test_fastapi_demo.py
  requirements.txt
Labels: bot is merging ⏳

#356 [14.0][FIX] fastapi
  fastapi/__init__.py
  fastapi/__manifest__.py
  fastapi/context.py
  fastapi/fastapi_dispatcher.py
  fastapi/http.py
  fastapi/models/fastapi_endpoint.py
  fastapi/routers/demo_router.py
Labels: merged 🎉
