Repository OCA/rest-framework, pull requests merged in 2023-08, with the labels that each got.

#363 [16.0][IMP] test_extendable_pydantic_fastapi: new test case
  test_extendable_pydantic_fastapi/routers.py
  test_extendable_pydantic_fastapi/schemas.py
  test_extendable_pydantic_fastapi/tests/test_user.py
Labels: bot is merging ⏳

#364 [16.0][ADD] New class StrictExtendableBaseModel into extendable_fastapi
  extendable_fastapi/__init__.py
  extendable_fastapi/__manifest__.py
  extendable_fastapi/schemas.py
  extendable_fastapi/tests/__init__.py
  extendable_fastapi/tests/test_strict_extendable_base_model.py
  fastapi/README.rst
  requirements.txt
Labels: approved, bot is merging ⏳

#366 [16.0][REF] extendable_fastapi: unit tests
  extendable_fastapi/__manifest__.py
  extendable_fastapi/models/__init__.py
  extendable_fastapi/models/fastapi_endpoint_demo.py
  extendable_fastapi/readme/CONTRIBUTORS.rst
  extendable_fastapi/tests/__init__.py
  extendable_fastapi/tests/routers.py
  extendable_fastapi/tests/schemas.py
  extendable_fastapi/tests/test_generic_extendable.py
  requirements.txt
  setup/test_extendable_pydantic_fastapi/odoo/addons/test_extendable_pydantic_fastapi
  setup/test_extendable_pydantic_fastapi/setup.py
  test_extendable_pydantic_fastapi/README.rst
  test_extendable_pydantic_fastapi/__init__.py
  test_extendable_pydantic_fastapi/__manifest__.py
  test_extendable_pydantic_fastapi/i18n/test_extendable_pydantic_fastapi.pot
  test_extendable_pydantic_fastapi/models/__init__.py
  test_extendable_pydantic_fastapi/readme/CONTRIBUTORS.rst
  test_extendable_pydantic_fastapi/readme/DESCRIPTION.rst
  test_extendable_pydantic_fastapi/schemas.py
  test_extendable_pydantic_fastapi/static/description/icon.png
  test_extendable_pydantic_fastapi/static/description/index.html
  test_extendable_pydantic_fastapi/tests/__init__.py
Labels: bot is merging ⏳

#333 [13.0][IMP] rest_log: improve exceptions handling
  rest_log/components/service.py
  rest_log/exceptions.py
Labels: stale
