Repository OCA/rest-framework, pull requests merged in 2024-10, with the labels that each got.

#442 [16.0] [FIX] fastapi: Unflag save_session in routing info
  fastapi/models/fastapi_endpoint.py
  fastapi/readme/newsfragments/442.feature
  fastapi/views/fastapi_endpoint.xml
Labels: approved, ready to merge, bot is merging ⏳

#454 [17.0][FIX] fastapi: History file content
  fastapi/README.rst
  fastapi/readme/HISTORY.md
  fastapi/static/description/index.html
Labels: bot is merging ⏳

#453 [17.0][FIX] fastapi: Handle error occurring outside the fastapi processing
  fastapi/fastapi_dispatcher.py
Labels: bot is merging ⏳

#457 [17.0] fastapi: improve test client setup
  fastapi/tests/common.py
Labels: bot is merging ⏳

#460 Oca port from 16.0 to 17.0 pr 440 443 442
  fastapi/__manifest__.py
  fastapi/dependencies.py
  fastapi/fastapi_dispatcher.py
  fastapi/models/fastapi_endpoint.py
  fastapi/readme/newsfragments/440.bugfix
  fastapi/readme/newsfragments/442.feature
  fastapi/routers/demo_router.py
  fastapi/tests/test_fastapi.py
  fastapi/views/fastapi_endpoint.xml
  requirements.txt
Labels: bot is merging ⏳

#437 [17.0][MIG] pydantic: Migration to 17.0
  .pre-commit-config.yaml
  pydantic/README.rst
  pydantic/__manifest__.py
  pydantic/pyproject.toml
  pydantic/readme/CONTRIBUTORS.md
  pydantic/readme/CONTRIBUTORS.rst
  pydantic/readme/DESCRIPTION.md
  pydantic/readme/DESCRIPTION.rst
  pydantic/readme/ROADMAP.md
  pydantic/readme/ROADMAP.rst
  pydantic/readme/USAGE.md
  pydantic/readme/USAGE.rst
  pydantic/static/description/index.html
  requirements.txt
Labels: bot is merging ⏳

#464 [16.0] [IMP] fastapi: Factorize error handling and use it in tests with raise_server_exceptions=False
  fastapi/error_handlers.py
  fastapi/fastapi_dispatcher.py
  fastapi/tests/common.py
  fastapi/tests/test_fastapi_demo.py
Labels: approved, bot is merging ⏳
