Repository OCA/rest-framework, pull requests merged in 2025-04, with the labels that each got.

#504 [16.0] [FIX] fastapi Headers may have multiple keys
  fastapi/fastapi_dispatcher.py
Labels: approved, bot is merging ⏳

#517 [17.0][FW] fastapi: multiple ports from 16.0
  .oca/oca-port/blacklist/fastapi.json
  fastapi/fastapi_dispatcher.py
  fastapi/tests/test_fastapi_demo.py
Labels: bot is merging ⏳

#500 [16.0] [FIX] extendable_fastapi: Inherit from last declared fastapi dispatcher
  extendable_fastapi/fastapi_dispatcher.py
Labels: bot is merging ⏳

#495 [18.0][MIG] pydantic
  pydantic/README.rst
  pydantic/__init__.py
  pydantic/__manifest__.py
  pydantic/i18n/it.po
  pydantic/i18n/pydantic.pot
  pydantic/pyproject.toml
  pydantic/readme/CONTRIBUTORS.md
  pydantic/readme/DESCRIPTION.md
  pydantic/readme/ROADMAP.md
  pydantic/readme/USAGE.md
  pydantic/static/description/icon.png
  pydantic/static/description/index.html
  pydantic/utils.py
  requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#513 [14.0][FIX] base_rest_pydantic: fix `_` being overridden in the `to_response` function
  base_rest_pydantic/restapi.py
  base_rest_pydantic/tests/test_response.py
Labels: approved, ready to merge, bot is merging ⏳

#496 [18.0][MIG] extendable
  .pre-commit-config.yaml
  extendable/README.rst
  extendable/__init__.py
  extendable/__manifest__.py
  extendable/i18n/extendable.pot
  extendable/models/__init__.py
  extendable/models/extendable_registry_loader.py
  extendable/models/ir_http.py
  extendable/pyproject.toml
  extendable/readme/CONTRIBUTORS.md
  extendable/readme/DESCRIPTION.md
  extendable/readme/ROADMAP.md
  extendable/readme/USAGE.md
  extendable/registry.py
  extendable/static/description/icon.png
  extendable/static/description/index.html
  extendable/tests/__init__.py
  extendable/tests/common.py
  requirements.txt
Labels: approved, bot is merging ⏳
