Repository OCA/rest-framework, pull requests merged in 2025-02, with the labels that each got.

#471 [18.0][MIG] fastapi: Migration to 18.0
  fastapi/README.rst
  fastapi/__init__.py
  fastapi/__manifest__.py
  fastapi/context.py
  fastapi/demo/fastapi_endpoint_demo.xml
  fastapi/dependencies.py
  fastapi/depends.py
  fastapi/error_handlers.py
  fastapi/fastapi_dispatcher.py
  fastapi/i18n/fastapi.pot
  fastapi/i18n/it.po
  fastapi/models/__init__.py
  fastapi/models/fastapi_endpoint.py
  fastapi/models/fastapi_endpoint_demo.py
  fastapi/models/ir_rule.py
  fastapi/models/res_lang.py
  fastapi/pyproject.toml
  fastapi/readme/CONTRIBUTORS.md
  fastapi/readme/DESCRIPTION.md
  fastapi/readme/HISTORY.md
  fastapi/readme/ROADMAP.md
  fastapi/readme/USAGE.md
  fastapi/readme/newsfragments/.gitignore
  fastapi/routers/__init__.py
  fastapi/routers/demo_router.py
  fastapi/schemas.py
  fastapi/security/fastapi_endpoint.xml
  fastapi/security/ir_rule+acl.xml
  fastapi/security/res_groups.xml
  fastapi/static/description/endpoint_create.png
  fastapi/static/description/icon.png
  fastapi/static/description/index.html
  fastapi/tests/__init__.py
  fastapi/tests/common.py
  fastapi/tests/test_fastapi.py
  fastapi/tests/test_fastapi_demo.py
  fastapi/views/fastapi_endpoint.xml
  fastapi/views/fastapi_endpoint_demo.xml
  fastapi/views/fastapi_menu.xml
  requirements.txt
  test-requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#497 [FIX] base_rest: restoring the component_database provoked fails with other modules
  base_rest/tests/common.py
Labels: approved, bot is merging ⏳

#425 [14.0][IMP] base_rest: show first-level menu to admins only
  base_rest/README.rst
  base_rest/readme/DESCRIPTION.rst
  base_rest/static/description/index.html
  base_rest/views/base_rest_view.xml
Labels: approved, bot is merging ⏳, no stale
